### ISSUE TITLE
Paper selection for catalog UI

### ISSUE THREAD

**Issue by mehmetemreakbulut** [yusuferdemnacar/Social-Network-Analysis-on-Research#11]
Papers selected after search operations can be added to catalog. 

- [ ] Papers will be added to catalog by selecting them via selection icon.
- [ ] Catalog view will show the papers selected.

**Deadline:** 05.12.2022 12.00

Reviewer: @yusuferdemnacar

**Comment by yusuferdemnacar** [comment]
This issue is deprecated and will be replaced by new UI issues.
