### ISSUE TITLE
Setup Remote Database

### ISSUE THREAD

**Issue by mehmetemreakbulut** [yusuferdemnacar/Social-Network-Analysis-on-Research#21]
For development purposes a remote database must be used to be sync with data.
Also set env variables with django environ
### Catalog Base
- [x] Create EC2 Server and Install Postgresql on it
- [x] Connect Django to Remote DB

**Reviewer** @yusuferdemnacar 
**Deadline:** 7.12.2022 15.00

**Comment by yusuferdemnacar** [comment]
Done.
