### ISSUE TITLE
Neo4j Setup and Connection

### ISSUE THREAD

**Issue by mehmetemreakbulut** [yusuferdemnacar/Social-Network-Analysis-on-Research#28]
Neo4j setup was done in last week. I will create a Neo4j Client as a module.
### Neo4j Client
- [x] Create Node Functionality
- [x] Create Relationship Functionality
- [x] Get Node Info Functionality

**Reviewer** @yusuferdemnacar 
**Deadline:** 20.12.2022 11.00

**Comment by yusuferdemnacar** [comment]
The task is done, however, we decided to implement a separate neo4j database rather than using auraDB, so I am closing this issue.
