### ISSUE TITLE
Adding Author Nodes

### ISSUE THREAD

**Issue by mehmetemreakbulut** [yusuferdemnacar/Social-Network-Analysis-on-Research#36]
We decided to add Author nodes to the build graph process.

### Todo
- [x] Fetching Author Data from Semantic Scholar
- [x] Adding Author Nodes to Graph DB

**Reviewer** @mehmetemreakbulut 
**Deadline:** 03.01.2023 11.00

**Comment by yusuferdemnacar** [comment]
The task is done, and we will be moving on to the tasks for the winter break.
